[package]
name = "sfx-server"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.9", features = ["blocking"] }
axum = "0.4.6"
tokio = { version = "1.0", features = ["full"] }