name: pillow
description: A flutter plugin for dream project.
version: 0.0.1
homepage: xyz.sfx.plw

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: xyz.sfx.plw
        pluginClass: PillowPlugin
      ios:
        pluginClass: PillowPlugin
      macos:
        pluginClass: PillowPlugin
      windows:
        pluginClass: PillowPlugin
      linux:
        pluginClass: PillowPlugin
      web:
        pluginClass: PillowWeb
        fileName: pillow_web.dart