name: sfxui

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  provider:
  url_launcher: ^6.0.20
  js:

flutter:
  uses-material-design: true
  fonts:
    - family: Cookie
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf