name: pillow_example
description: Demonstrates how to use the pillow plugin.

publish_to: 'none'

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pillow:
    path: ../
  ffi:
  ffigen: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

ffigen:
  name: CouchLibrary
  output: 'lib/gen/generated_bindings.dart'
  headers:
    entry-points:
      - '../../couch/out/include/markdown.h'
